import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "@/lib/todo-context"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Todo List",
    description: "Generated by will harper",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full p-8 selection:bg-fuchsia-900 selection:text-white flex flex-col">
                <div className="flex flex-row justify-between items-center mb-4">
                    <Link href="/">
                        <h1 className="hover:text-fuchsia-800 transition-colors font-extrabold font-sans text-sm lg:text-3xl">Shopping List</h1>
                    </Link>
                    <Link href="./add">
                        <button className="py-3 px-10 w-fit hover:bg-fuchsia-700 transition-all cursor-pointer bg-fuchsia-900 text-white rounded-full font-bold active:scale-95">add item</button>
                    </Link>
                </div>
                <TodoProvider>
                    {children}
                </TodoProvider>
            </body>
        </html>
    );
}
